name = "RandomNumbers"
uuid = "e6cf234a-135c-5ec9-84dd-332b85af5143"
author = ["Sunoru <s@sunoru.com>"]
repo = "https://github.com/JuliaRandom/RandomNumbers.jl.git"
version = "1.5.3"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Requires = "1"
julia = "1"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Printf"]
